apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: jogeshgupta963/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./**/*.py"
            dest: .
    - image: jogeshgupta963/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jogeshgupta963/admin
      context: admin
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./**/*.py"
            dest: .
